export default [
    { name: "isShow", defaultVal: false },
    { name: "withOverlay", defaultVal: false },
    { name: "width", defaultVal: 300 },
    { name: "themeColor", defaultVal: "", cascadeAttr: ["titleBarColor", "confirmBtnColor"] },
    { name: "titleBarColor", defaultVal: "" },
    { name: "title", defaultVal: "Message" },
    { name: "content", defaultVal: "content" },
    { name: "isShowCancelBtn", defaultVal: true },
    { name: "cancelBtnColor", defaultVal: "" },
    { name: "cancelBtnTxt", defaultVal: "cancel" },
    { name: "isShowConfirmBtn", defaultVal: true },
    { name: "confirmBtnColor", defaultVal: "" },
    { name: "confirmBtnTxt", defaultVal: "confirm" },
    { name: "resolve", defaultVal: () => { } },
    { name: "reject", defaultVal: () => { } },
];